apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  # initContainers:
  # - name: init-service
  #   image: busybox
  #   command: ['sh', '-c', 'until nslookup nginx-svc; do echo waiting for nginx-svc; sleep 1; done']