apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: my-app
        image: nginx:latest
        ports:
        - containerPort: 80
      initContainers:
      - name: check-service
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup nginx-svc; do sleep 2; done;']