apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: check-service
        image: busybox
        command: ['sh', '-c', 'until nslookup nginx-svc; do sleep 1; done']
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80