apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-multitool
  template:
    metadata:
      labels:
        app: be-multitool
    spec:
      containers:
      - name: be-multitool
        image: wbitt/network-multitool
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"
