apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ingress-configmap
  name: config
data:
  config: |
    address-pools:
    - name: ingress-nginx
      protocol: layer2
      addresses:
      - 192.168.1.240-192.168.1.250