apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: app
spec:
  ports:
    - name: web-nginx
      port: 9001
      targetPort: 80
    - name: web-mtools
      port: 9002
      targetPort: 8080
  selector:
    app: main