apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-communication
  namespace: web
spec:
  podSelector:
    matchLabels: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: data
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: data
